spring:
  application:
    name: SpringJdbcCrudOperations

datasource:
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/spring-jdbc?useSSL=false
  username: nitin
  password: nitin
